// The officer service (OFFICER_URL, default :4004): the HUMAN approver's signing seat (Phase 3, builder B).
// It loads ONLY the root .env + xrpl/.env.officer (loadEnv("officer")), holds only OFFICER_SEED (weight 1 of quorum 3 on
// agent_account) and refuses to start if any other *_SEED is in its environment. Each HTTP call marked [HUMAN CLICK] below
// stands for a click by the human officer; it is logged as such.
//
// Click authentication (Phase 3 fixes): every [HUMAN CLICK] route requires the header `x-officer-token` equal to
// OFFICER_CLICK_TOKEN, which exists ONLY in xrpl/.env.officer (generated by `npm run setup:xrpl`; never printed). It is
// compared in constant time. The officer's own click CLI (scripts/officer-click.ts, `npm run officer:click`) loads it; the
// agent processes (xrpl service, demo runner) never do, so they cannot press the officer's buttons over HTTP. A request that
// carries an `Origin` header (i.e. from a browser page) is refused too, and the custom header makes every click a
// non-simple request, so a web page cannot forge one (no CORS is registered).
//
//   GET  /health                       -> {ok, role:"officer", signer_address, agent_account, signer_list, cosigner_url, xrpl_service_url}
//   GET  /approvals                    -> {ok, approvals: PendingApproval[]}  (newest first; the officer's inbox)
//   POST /approvals/:decision_id       [HUMAN CLICK] {amount, destination, decision_hash} = what the officer saw and approves.
//        The officer verifies the pending decision itself (hash recomputed, registry wallet from its own pinned accounts
//        file, contract payee, and the CO-SIGNER's own record of the refusal: GET :4002/over-limit/:decision_id), refuses
//        unless the click's {amount, destination, decision_hash} equal that verified intent, claims it once (single use;
//        expires 24 h after the pending decision), then asks the xrpl service (:4001) to rebuild and execute it.
//        200 {ok, approval_id, decision (the NEW released decision), explorer_url, engine_result} | 400/401/404/409/410/422/502/503
//   POST /approvals/:decision_id/sign  {tx_blob, approval_id}  (called by the xrpl service during that execution, not a click;
//        bound to the approved intent in this process's memory) 200 {ok, signed_blob} only if the tx is EXACTLY the approved
//        payment (fresh, agent-signed); 422 {ok:false, problems}
//   GET  /agent/status                 -> {ok, config: CANONICAL|REVOKED|OTHER, master_disabled, entries, quorum}
//   POST /agent/revoke                 [HUMAN CLICK] kill switch: SignerListSet {cosigner:2, officer:1} q3 (officer + co-signer)
//   POST /agent/restore                [HUMAN CLICK] SignerListSet back to {agent:1, cosigner:2, officer:1} q3 (idempotent)
//        200 {ok, target, changed, before, after, master_disabled, engine_result, final, tx_hash, explorer_url, message}
//   POST /payees/:ein/change-requests/:request_id/resolve {decision:"approve"|"reject", confirm_freeze?}   [HUMAN CLICK]
//        wraps resolvePayeeChange(): signs the resolution with the officer key and delivers it to the co-signer. "approve"
//        needs confirm_freeze: true (in this build an approved change keeps the EIN frozen: re-onboarding is not automated)
//   POST /escrow/milestones/:milestone_id/approve-release   [HUMAN CLICK]   SIMULATED escrow (CTT test token): the officer
//        reads the co-signer's escrow record and the escrow ON-LEDGER, checks the destination is its pinned registry wallet,
//        signs a MilestoneReleaseApproval bound to that escrow and delivers it to the co-signer (POST :4002/escrow/release-approval),
//        which reveals the fulfillment only while it holds such an approval. 200 {ok, approval, escrow, cosigner} | 401/404/409/502
//
// Run: npm run officer   (repo root)
import { createHash, timingSafeEqual } from "node:crypto";
import Fastify, { type FastifyReply, type FastifyRequest } from "fastify";
import { Wallet, decode, type Client, type Transaction } from "xrpl";
import { loadEnv } from "../env";
import { loadRegistry, nonprofitByEin } from "../lib/registry";
import { connect, rlusd, sourceTag } from "../lib/xrpl";
import { COLL, openMongo, type MongoHandle } from "../lib/mongo";
import { readLedgerView } from "../cosigner/context";
import { EIN_RE } from "../lib/credentials";
import { listPendingApprovals } from "../agent/approvals";
import { claimApproval, matchApprovedTx, verifyPending, SIGN_WINDOW_MS, type ApprovedIntent, type CosignerOverLimitRecord } from "./approvals";
import { setAgentSignerList, signerListStatus } from "./governance";
import { resolvePayeeChange } from "./resolve";
import { signReleaseApproval, CTT_CURRENCY } from "../lib/escrow";
import { toMicro } from "../lib/ledgerScan";

loadEnv("officer");

function die(msg: string): never {
  console.error(`[officer] ${msg}`);
  process.exit(1);
}

const foreign = Object.keys(process.env).filter((k) => k.endsWith("_SEED") && k !== "OFFICER_SEED");
if (foreign.length) die(`refusing to start: other signing seeds are present in this process's environment (${foreign.join(", ")})`);
const seed = process.env.OFFICER_SEED;
if (!seed) die('OFFICER_SEED missing: run "npm run setup:xrpl" to generate xrpl/.env.officer');
const officer = Wallet.fromSeed(seed);
delete process.env.OFFICER_SEED;
const reg = loadRegistry(); // pinned at startup: the officer compares destinations with THIS copy
if (officer.address !== reg.signers.officer.address) die(`OFFICER_SEED derives ${officer.address}, not the registry officer ${reg.signers.officer.address}`);
const clickToken = process.env.OFFICER_CLICK_TOKEN ?? "";
delete process.env.OFFICER_CLICK_TOKEN;
if (!/^[0-9a-f]{64}$/.test(clickToken)) die('OFFICER_CLICK_TOKEN missing or malformed in xrpl/.env.officer: run "npm run setup:xrpl" (it adds one; never printed)');
const tokenDigest = createHash("sha256").update(clickToken).digest();

const url = (k: string, d: string) => (process.env[k] ?? d).replace(/\/$/, "");
const COSIGNER_URL = url("COSIGNER_URL", "http://localhost:4002");
const XRPL_SERVICE_URL = url("XRPL_SERVICE_URL", "http://localhost:4001");
const R = rlusd();
const TAG = sourceTag();

const log = (m: string) => console.log(`[officer] ${new Date().toISOString()} ${m}`);
const click = (what: string) => log(`[HUMAN CLICK] the officer ${what}`);
const scrub = (m: string) => m.replace(/mongodb(\+srv)?:\/\/\S+/g, "<uri>");

/** A [HUMAN CLICK] must carry the officer's click credential (x-officer-token) and must not come from a browser page. */
function clickAuthProblem(req: FastifyRequest): string | null {
  if (req.headers.origin !== undefined) return `a request from a web page (Origin ${String(req.headers.origin).slice(0, 80)}) cannot press the officer's buttons`;
  const h = req.headers["x-officer-token"];
  const given = typeof h === "string" ? h : "";
  if (!given) return "missing x-officer-token: officer clicks come from the officer's own click CLI (npm run officer:click)";
  const ok = timingSafeEqual(createHash("sha256").update(given).digest(), tokenDigest);
  return ok ? null : "x-officer-token does not match the officer's credential";
}

/** The co-signer's own record of an over-limit refusal (GET /over-limit/:decision_id). null + error if unreachable. */
async function cosignerOverLimit(decision_id: string): Promise<{ refusals: CosignerOverLimitRecord[] } | { error: string }> {
  try {
    const r = await fetch(`${COSIGNER_URL}/over-limit/${encodeURIComponent(decision_id)}`, { signal: AbortSignal.timeout(10000) });
    if (r.status === 404) return { refusals: [] };
    const j = (await r.json().catch(() => ({}))) as { ok?: boolean; refusals?: CosignerOverLimitRecord[]; message?: string };
    if (!r.ok || !j.ok || !Array.isArray(j.refusals)) return { error: `co-signer GET /over-limit answered HTTP ${r.status} ${j.message ?? ""}` };
    return { refusals: j.refusals };
  } catch (e) {
    return { error: `co-signer at ${COSIGNER_URL} unreachable (${(e as Error).message})` };
  }
}

let client: Client | null = null;
async function xrpl(): Promise<Client> {
  if (!client || !client.isConnected()) {
    if (client) await client.disconnect().catch(() => undefined);
    client = await connect();
  }
  return client;
}

// Governance actions one at a time; approvals one per decision at a time (the /sign callback must stay reachable).
let govQueue: Promise<unknown> = Promise.resolve();
const govSerial = <T>(fn: () => Promise<T>): Promise<T> => {
  const run = govQueue.then(fn, fn);
  govQueue = run.catch(() => undefined);
  return run;
};
const inFlight = new Set<string>();
/** Approved intents, in THIS process's memory only: what the officer will sign for each approval. */
const intents = new Map<string, ApprovedIntent>();

function portFromUrl(): { host: string; port: number } {
  try {
    const u = new URL(process.env.OFFICER_URL ?? "http://localhost:4004");
    return { host: u.hostname, port: Number(u.port || 4004) };
  } catch {
    return { host: "localhost", port: 4004 };
  }
}

async function main() {
  let mongo: MongoHandle;
  try {
    mongo = await openMongo("divhacks-officer");
  } catch (e) {
    die(`cannot reach MongoDB (${scrub((e as Error).message)})`);
  }
  const db = mongo.db;
  // An approval claimed by an earlier officer process whose execution never finished: its approved intent lived only in that
  // process's memory, so nothing can be signed for it any more. Release it for a new click (the co-signer's live
  // co-signature tracking and the on-ledger memo scan still prevent a double payment if an earlier attempt lands).
  const stuck = await db.collection(COLL.pendingApprovals).updateMany(
    { status: "approved" },
    { $set: { status: "failed", failure: "the officer service restarted before this approval was executed; its approved intent (kept only in that process's memory) is gone. Approve again to retry." } },
  );
  if (stuck.modifiedCount) log(`released ${stuck.modifiedCount} approval(s) left in "approved" by an earlier officer process (status -> failed; approve again to retry)`);
  const app = Fastify({ logger: false, bodyLimit: 64 * 1024 });
  const fail = (reply: FastifyReply, status: number, error: string, message: string, extra: Record<string, unknown> = {}) => reply.code(status).send({ ok: false, error, message, ...extra });
  /** Returns true (and answers 401/403) if the click is not authenticated. */
  const refuseClick = (req: FastifyRequest, reply: FastifyReply, what: string): boolean => {
    const why = clickAuthProblem(req);
    if (!why) return false;
    log(`[REFUSED CLICK] ${what}: ${why}`);
    void fail(reply, req.headers.origin !== undefined ? 403 : 401, "officer_auth_required", why);
    return true;
  };

  app.get("/health", async () => {
    let signer_list: unknown = null;
    try {
      signer_list = await signerListStatus(await xrpl(), reg);
    } catch (e) {
      signer_list = { error: (e as Error).message };
    }
    return { ok: true, role: "officer", signer_address: officer.address, weight: reg.signers.officer.weight, agent_account: reg.agent_account, signer_list, cosigner_url: COSIGNER_URL, xrpl_service_url: XRPL_SERVICE_URL, approvals_in_memory: intents.size };
  });

  app.get("/approvals", async () => ({ ok: true, approvals: await listPendingApprovals(db) }));

  app.post("/approvals/:decision_id", async (req, reply) => {
    const { decision_id } = req.params as { decision_id: string };
    if (refuseClick(req, reply, `approve over-limit decision ${decision_id}`)) return reply;
    if (!/^[A-Za-z0-9_.:-]{1,128}$/.test(decision_id)) return fail(reply, 400, "bad_request", "bad decision_id");
    // The click carries what the human saw: the officer approves exactly that, or nothing.
    const seen = (req.body ?? {}) as { amount?: unknown; destination?: unknown; decision_hash?: unknown };
    if (typeof seen.amount !== "string" || typeof seen.destination !== "string" || typeof seen.decision_hash !== "string") {
      return fail(reply, 400, "bad_request", "the click must carry what the officer approves: {amount, destination, decision_hash} (npm run officer:click -- approve <decision_id> shows them first)");
    }
    if (inFlight.has(decision_id)) return fail(reply, 409, "in_progress", `an approval for ${decision_id} is already being executed`);
    inFlight.add(decision_id);
    try {
      click(`approves over-limit decision ${decision_id}: ${seen.amount} RLUSD -> ${seen.destination} (dh ${seen.decision_hash.slice(0, 12)}...)`);
      const cr = await cosignerOverLimit(decision_id);
      if ("error" in cr) {
        log(`approval of ${decision_id} NOT possible: ${cr.error}`);
        return fail(reply, 503, "cosigner_unavailable", `cannot read the co-signer's own record of this refusal: ${cr.error}; nothing approved`);
      }
      const v = await verifyPending(db, reg, decision_id, Date.now(), cr.refusals);
      if (!v.ok) {
        log(`approval of ${decision_id} NOT possible: ${v.error}: ${v.message}`);
        return fail(reply, v.status, v.error, v.message);
      }
      const seenOk = /^\d{1,9}(\.\d{1,6})?$/.test(seen.amount) && toMicro(seen.amount) === toMicro(v.intent.amount) && seen.destination === v.intent.destination && seen.decision_hash === v.intent.decision_hash;
      if (!seenOk) {
        log(`approval of ${decision_id} NOT possible: the click (${seen.amount} -> ${seen.destination}, dh ${seen.decision_hash.slice(0, 12)}) differs from the verified pending payment (${v.intent.amount} -> ${v.intent.destination}, dh ${v.intent.decision_hash.slice(0, 12)})`);
        return fail(reply, 409, "approval_mismatch", `what the officer approved (${seen.amount} RLUSD -> ${seen.destination}) is not the verified pending payment (${v.intent.amount} RLUSD -> ${v.intent.destination}, dh ${v.intent.decision_hash.slice(0, 12)}...); nothing approved`);
      }
      for (const n of v.notes) log(`verified: ${n}`);
      const claim = await claimApproval(db, decision_id, officer.address, "officer service (HTTP click)");
      if (!claim) return fail(reply, 409, "not_claimable", `decision ${decision_id} is no longer pending (approved elsewhere, executed or expired)`);
      const intent: ApprovedIntent = { ...v.intent, approval_id: claim.approval_id, approved_at: claim.approved_at, approved_ms: Date.now(), signed: false };
      intents.set(decision_id, intent);
      log(`approval ${claim.approval_id} recorded (single use); asking the xrpl service to rebuild the payment fresh and execute it`);
      let res: Response;
      try {
        res = await fetch(`${XRPL_SERVICE_URL}/approvals/${encodeURIComponent(decision_id)}/execute`, {
          method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ approval_id: claim.approval_id }), signal: AbortSignal.timeout(240000),
        });
      } catch (e) {
        await db.collection("pending_approvals").updateOne({ decision_id, "approval.approval_id": claim.approval_id, status: "approved" }, { $set: { status: "failed", failure: `xrpl service unreachable: ${(e as Error).message}` } });
        return fail(reply, 502, "xrpl_service_unreachable", `xrpl service at ${XRPL_SERVICE_URL} unreachable (${(e as Error).message}); approval released for a retry`);
      }
      const j = (await res.json().catch(() => ({}))) as { ok?: boolean; decision?: { decision_id: string; outcome: string; xrpl_tx_hash: string | null; ledger_result: string | null; signers: string[] }; explorer_url?: string | null; engine_result?: string | null; message?: string; error?: string };
      log(`execution of ${decision_id}: ${j.ok ? "RELEASED" : "NOT released"} ${j.decision ? `(${j.decision.decision_id}, ${j.decision.ledger_result ?? j.error}, signers ${j.decision.signers?.join("+")})` : `(${j.error ?? res.status}: ${j.message ?? ""})`}${j.explorer_url ? ` ${j.explorer_url}` : ""}`);
      return reply.code(res.ok ? 200 : res.status).send({ ok: !!j.ok, approval_id: claim.approval_id, decision: j.decision ?? null, explorer_url: j.explorer_url ?? null, engine_result: j.engine_result ?? null, message: j.message ?? null, error: j.error ?? null });
    } finally {
      inFlight.delete(decision_id);
    }
  });

  app.post("/approvals/:decision_id/sign", async (req, reply) => {
    const { decision_id } = req.params as { decision_id: string };
    const body = req.body as { tx_blob?: unknown; approval_id?: unknown } | null;
    const intent = intents.get(decision_id);
    if (!intent) return fail(reply, 404, "no_approval", `the officer has not approved ${decision_id} in this session`);
    if (!body || body.approval_id !== intent.approval_id) return fail(reply, 409, "approval_mismatch", "approval_id does not match the officer's approval");
    if (intent.signed) return fail(reply, 409, "already_signed", `approval ${intent.approval_id} was already used to sign a transaction (single use)`);
    if (Date.now() - intent.approved_ms > SIGN_WINDOW_MS) return fail(reply, 410, "sign_window_closed", `approval ${intent.approval_id} is older than ${SIGN_WINDOW_MS / 60000} minutes`);
    if (Date.parse(intent.expires_at) <= Date.now()) return fail(reply, 410, "expired", `the approval window closed at ${intent.expires_at}`);
    if (typeof body.tx_blob !== "string" || !/^[0-9A-Fa-f]{2,20000}$/.test(body.tx_blob)) return fail(reply, 400, "bad_request", "tx_blob must be hex");
    let tx: Record<string, unknown>;
    try {
      tx = decode(body.tx_blob) as Record<string, unknown>;
    } catch (e) {
      return fail(reply, 400, "bad_request", `tx_blob does not decode: ${(e as Error).message}`);
    }
    let lv;
    try {
      lv = await readLedgerView(await xrpl(), reg.agent_account);
    } catch (e) {
      return fail(reply, 503, "ledger_unavailable", (e as Error).message);
    }
    const problems = matchApprovedTx(tx, intent, { agentAccount: reg.agent_account, rlusd: R, sourceTag: TAG, signers: { agent: reg.signers.agent.address, officer: officer.address }, ledger: lv });
    if (problems.length) {
      log(`REFUSED to sign for ${decision_id}: ${problems.join("; ")}`);
      return reply.code(422).send({ ok: false, error: "tx_does_not_match_approval", problems, message: problems.join("; ") });
    }
    intent.signed = true; // single use, before the signature leaves this process
    const bare = { ...tx };
    delete bare.Signers;
    const signed_blob = officer.sign(bare as unknown as Transaction, true).tx_blob;
    await db.collection("pending_approvals").updateOne({ decision_id }, { $set: { officer_signed: { at: new Date().toISOString(), sequence: tx.Sequence, last_ledger_sequence: tx.LastLedgerSequence } } }).catch(() => undefined);
    log(`signed the rebuilt payment for ${decision_id}: exactly the approved ${intent.amount} RLUSD -> ${intent.destination}, memo dh ${intent.decision_hash.slice(0, 12)}..., Sequence ${String(tx.Sequence)}`);
    return reply.send({ ok: true, signer: "officer", signer_address: officer.address, signed_blob });
  });

  app.get("/agent/status", async (_req, reply) => {
    try {
      return { ok: true, ...(await signerListStatus(await xrpl(), reg)) };
    } catch (e) {
      return fail(reply, 503, "ledger_unavailable", (e as Error).message);
    }
  });

  for (const [path, target] of [["/agent/revoke", "REVOKED"], ["/agent/restore", "CANONICAL"]] as const) {
    app.post(path, (req, reply) =>
      govSerial(async () => {
        if (refuseClick(req, reply, `${path}`)) return reply;
        click(target === "REVOKED" ? "pulls the KILL SWITCH: revoke the agent key from agent_account's signer list" : "restores the agent key to agent_account's signer list");
        try {
          const r = await setAgentSignerList(target, { client: await xrpl(), officer, reg, cosignerUrl: COSIGNER_URL, log });
          log(`${path}: ${r.message}${r.explorer_url ? ` ${r.explorer_url}` : ""}`);
          return reply.code(r.ok ? 200 : 502).send(r);
        } catch (e) {
          return fail(reply, 503, "governance_failed", (e as Error).message);
        }
      }),
    );
  }

  app.post("/payees/:ein/change-requests/:request_id/resolve", async (req, reply) => {
    const { ein, request_id } = req.params as { ein: string; request_id: string };
    if (refuseClick(req, reply, `resolve payee change request ${request_id}`)) return reply;
    const body = (req.body ?? {}) as { decision?: unknown; confirm_freeze?: unknown };
    const decision = body.decision;
    if (!EIN_RE.test(ein)) return fail(reply, 400, "bad_request", "ein must be NN-NNNNNNN");
    if (decision !== "approve" && decision !== "reject") return fail(reply, 400, "bad_request", 'body must be {decision: "approve"|"reject"}');
    if (decision === "approve" && body.confirm_freeze !== true) {
      return fail(reply, 400, "confirm_freeze_required", "approve keeps every payment to this EIN frozen until the requested wallet is re-onboarded, which this build does not automate (resolutions are final). Send {decision:\"approve\", confirm_freeze:true} to do it anyway; reject is the normal answer to an unverified request");
    }
    click(`resolves payee change request ${request_id} for EIN ${ein}: ${decision}`);
    const existing = await db.collection("payee_change_requests").findOne({ request_id }, { projection: { _id: 0, ein: 1 } });
    if (existing && existing.ein !== ein) return fail(reply, 409, "ein_mismatch", `request ${request_id} is for EIN ${String(existing.ein)}, not ${ein}`);
    const r = await resolvePayeeChange(db, officer, request_id, decision, COSIGNER_URL);
    if (!r.ok) return fail(reply, r.status, r.error, r.message);
    if (r.request.ein !== ein) return fail(reply, 409, "ein_mismatch", `request ${request_id} is for EIN ${r.request.ein}`);
    log(`payee change ${request_id}: ${r.message}; co-signer ${r.cosigner.delivered ? "verified the signature" : `not confirmed (${r.cosigner.message ?? ""})`}`);
    return reply.send({ ok: true, request: r.request, message: r.message, cosigner: r.cosigner });
  });

  // SIMULATED escrow (CTT test token, not RLUSD): the officer approves the release of one milestone escrow.
  app.post("/escrow/milestones/:milestone_id/approve-release", async (req, reply) => {
    const { milestone_id } = req.params as { milestone_id: string };
    if (refuseClick(req, reply, `approve the release of milestone ${milestone_id}`)) return reply;
    if (!/^[A-Za-z0-9_.:-]{1,128}$/.test(milestone_id)) return fail(reply, 400, "bad_request", "bad milestone_id");
    click(`approves the release of milestone escrow ${milestone_id} (simulated escrow, CTT test token)`);
    // 1. What the co-signer co-signed for this milestone (its own record; no preimages in it).
    let ms: { milestone_id: string; condition: string; create: { sequence: number; destination?: string; amount?: string; ctr?: string; ein?: string } | null; finish: unknown; cancel: unknown } | undefined;
    try {
      const r = await fetch(`${COSIGNER_URL}/escrow`, { signal: AbortSignal.timeout(10000) });
      const j = (await r.json()) as { milestones?: (typeof ms)[] };
      ms = j.milestones?.find((m) => m?.milestone_id === milestone_id);
    } catch (e) {
      return fail(reply, 502, "cosigner_unavailable", `co-signer at ${COSIGNER_URL} unreachable (${(e as Error).message})`);
    }
    if (!ms || !ms.create || typeof ms.create.sequence !== "number") return fail(reply, 404, "not_found", `the co-signer has no EscrowCreate record for milestone ${milestone_id}`);
    if (ms.cancel) return fail(reply, 409, "cancelled", `milestone ${milestone_id} was cancelled`);
    // 2. The escrow itself, read on-ledger by the officer.
    let node: { Destination: string; Amount: { currency?: string; issuer?: string; value?: string } | string; Condition?: string };
    try {
      const r = (await (await xrpl()).request({ command: "ledger_entry", escrow: { owner: reg.agent_account, seq: ms.create.sequence }, ledger_index: "validated" } as never)) as { result: { node: typeof node } };
      node = r.result.node;
    } catch (e) {
      const err = (e as { data?: { error?: string } }).data?.error;
      return fail(reply, err === "entryNotFound" ? 404 : 503, err === "entryNotFound" ? "escrow_not_found" : "ledger_unavailable", err === "entryNotFound" ? `escrow agent_account/${ms.create.sequence} is not on the validated ledger (already finished or cancelled?)` : (e as Error).message);
    }
    const amt = typeof node.Amount === "object" ? node.Amount : null;
    const problems: string[] = [];
    if (!amt || amt.currency !== CTT_CURRENCY || amt.issuer !== reg.city_issuer || typeof amt.value !== "string") problems.push(`the escrow does not hold ${CTT_CURRENCY} from city_issuer`);
    if ((node.Condition ?? "").toUpperCase() !== ms.condition.toUpperCase()) problems.push("the escrow's Condition is not the one the co-signer issued for this milestone");
    const hit = ms.create.ein ? nonprofitByEin(reg, ms.create.ein) : null;
    if (!hit || hit.np.address !== node.Destination) problems.push(`the escrow pays ${node.Destination}, not the registry wallet ${hit?.np.address ?? "(none)"} for EIN ${ms.create.ein ?? "?"} (officer's pinned accounts.testnet.json)`);
    if (ms.create.destination !== node.Destination || (amt && ms.create.amount && toMicro(ms.create.amount) !== toMicro(amt.value!))) problems.push("the on-ledger escrow differs from what the co-signer co-signed");
    if (problems.length) {
      log(`release of ${milestone_id} NOT approved: ${problems.join("; ")}`);
      return fail(reply, 409, "escrow_record_invalid", problems.join("; "));
    }
    // 3. Sign the approval bound to exactly this escrow and deliver it to the co-signer.
    const approval = signReleaseApproval(
      { milestone_id, owner: reg.agent_account, offer_sequence: ms.create.sequence, condition: ms.condition, destination: node.Destination, amount: amt!.value!, currency: CTT_CURRENCY, issuer: reg.city_issuer, ts: new Date().toISOString().replace(/\.\d{3}Z$/, "Z") },
      officer,
    );
    let delivered = false;
    let cosMessage: string | null = null;
    try {
      const r = await fetch(`${COSIGNER_URL}/escrow/release-approval`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ approval }), signal: AbortSignal.timeout(10000) });
      const j = (await r.json().catch(() => ({}))) as { ok?: boolean; message?: string };
      delivered = r.ok && j.ok === true;
      cosMessage = j.message ?? null;
    } catch (e) {
      cosMessage = `co-signer unreachable (${(e as Error).message})`;
    }
    log(`release approval for ${milestone_id} signed (escrow agent_account/${ms.create.sequence}: ${amt!.value} ${CTT_CURRENCY} -> ${hit!.key} ${node.Destination}); co-signer ${delivered ? "verified and recorded it" : `did NOT accept it (${cosMessage ?? ""})`}`);
    return reply.code(delivered ? 200 : 502).send({
      ok: delivered, approval, escrow: { owner: reg.agent_account, offer_sequence: ms.create.sequence, destination: node.Destination, amount: amt!.value, currency: CTT_CURRENCY, np_key: hit!.key, label: "simulated escrow (test token, not RLUSD)" },
      cosigner: { delivered, message: cosMessage },
    });
  });

  const shutdown = () => {
    const c = client;
    Promise.allSettled([app.close(), c?.disconnect(), mongo.close()]).finally(() => process.exit(0));
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
  const { host, port } = portFromUrl();
  if (port === 4003) die("port 4003 belongs to the iMessage service; set OFFICER_URL to another port");
  try {
    await app.listen({ port, host });
  } catch (e) {
    await mongo.close().catch(() => undefined);
    die(`failed to listen on ${host}:${port}: ${(e as Error).message}`);
  }
  log(`listening on http://${host}:${port} as officer ${officer.address} (weight ${reg.signers.officer.weight} of quorum ${reg.quorum}); co-signer ${COSIGNER_URL}; xrpl service ${XRPL_SERVICE_URL}; pid ${process.pid}`);
}

main().catch((e) => die(`startup failed: ${scrub((e as Error).message)}`));
